# version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: scraped_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hotel_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d hotel_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  scrapy:
    build: .
      # context: .
      # args:
      #   SERVICE: "scrapy crawl hotels_combined"
    # command: ["sleep", "infinity"]
    command: ["scrapy", "crawl", "hotels_combined"]
    container_name: scraper
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://myuser:mypassword@db:5432/hotel_db


  django:
    build: .
      # context: .
      # args:
      #   SERVICE: "python manage.py runserver 0.0.0.0:8000"
    command: ["sleep", "infinity"]
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    container_name: property_rewriter
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DB_HOST: scraped_db
      DB_NAME: hotel_db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      OLLAMA_URL: http://ollama:11434


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    command: serve


volumes:
  db_data:
